# Generated by Django 3.0.3 on 2020-03-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idC', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('image', models.ImageField(upload_to='photos_category')),
                ('parentCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idP', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('prize', models.FloatField()),
                ('image', models.ImageField(upload_to='photos_products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.Category')),
            ],
        ),
    ]
