# Generated by Django 3.0.3 on 2020-03-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0009_auto_20200304_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
